# 作業
- 新增一個欄位 `customized_age_grp`，把 `age` 分為 (0, 10], (10, 20], (20, 30], (30, 50], (50, 100] 這五組，
'(' 表示不包含, ']' 表示包含  
- Hints: 執行 ??pd.cut()，了解提供其中 bins 這個參數的使用方式

# [作業目標]
- 請同學試著查詢 pandas.cut 這個函數還有哪些參數, 藉由改動參數以達成目標
- 藉由查詢與改動參數的過程, 熟悉查詢函數的方法與理解參數性質, 並了解數值的離散化的調整工具

# [作業重點]
- 仿照 In[3], In[4] 的語法, 並設定 pd.cut 的參數以指定間距

In [0]:
# 載入套件
import os
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
# 初始設定 Ages 的資料
ages = pd.DataFrame({"age": [18,22,25,27,7,21,23,37,30,61,45,41,9,18,80,100]})

#### 等寬劃分

In [0]:
# 新增欄位 "equal_width_age", 對年齡做等寬劃分
ages["equal_width_age"] = pd.cut(ages["age"], 4)

In [0]:
# 觀察等寬劃分下, 每個種組距各出現幾次
ages["equal_width_age"].value_counts() # 每個 bin 的值的範圍大小都是一樣的

(6.907, 30.25]    10
(30.25, 53.5]      3
(76.75, 100.0]     2
(53.5, 76.75]      1
Name: equal_width_age, dtype: int64

#### 等頻劃分

In [0]:
# 新增欄位 "equal_freq_age", 對年齡做等頻劃分
ages["equal_freq_age"] = pd.qcut(ages["age"], 4)

In [0]:
# 觀察等頻劃分下, 每個種組距各出現幾次
ages["equal_freq_age"].value_counts() # 每個 bin 的資料筆數是一樣的

(42.0, 100.0]     4
(26.0, 42.0]      4
(20.25, 26.0]     4
(6.999, 20.25]    4
Name: equal_freq_age, dtype: int64

In [0]:
ages["customized_age_grp"] = pd.cut(ages["age"], 5)

**產生自訂分群**

*   新增一個欄位 customized_age_grp，把 age 分為 (0, 10], (10, 20], (20, 30], (30, 50], (50, 100] 這五組， '(' 表示不包含, ']' 表示包含
*   Hints: 執行 ??pd.cut()，了解提供其中 bins 這個參數的使用方式

In [11]:
bins = [0, 10, 20, 30, 50,100]
bins

[0, 10, 20, 30, 50, 100]

In [0]:
ages["customized_age_grp"] = pd.cut(ages["age"], bins)

In [15]:
ages

    age         eq_age customized_age_grp
0    18  (6.907, 38.0]           (10, 20]
1    22  (6.907, 38.0]           (20, 30]
2    25  (6.907, 38.0]           (20, 30]
3    27  (6.907, 38.0]           (20, 30]
4     7  (6.907, 38.0]            (0, 10]
5    21  (6.907, 38.0]           (20, 30]
6    23  (6.907, 38.0]           (20, 30]
7    37  (6.907, 38.0]           (30, 50]
8    30  (6.907, 38.0]           (20, 30]
9    61   (38.0, 69.0]          (50, 100]
10   45   (38.0, 69.0]           (30, 50]
11   41   (38.0, 69.0]           (30, 50]
12    9  (6.907, 38.0]            (0, 10]
13   18  (6.907, 38.0]           (10, 20]
14   80  (69.0, 100.0]          (50, 100]
15  100  (69.0, 100.0]          (50, 100]

In [17]:
ages["customized_age_grp"].value_counts()

(20, 30]     6
(50, 100]    3
(30, 50]     3
(10, 20]     2
(0, 10]      2
Name: customized_age_grp, dtype: int64

In [0]:
arr = ages["customized_age_grp"].unique()

In [29]:
print(type(ages["customized_age_grp"].unique()))

<class 'pandas.core.arrays.categorical.Categorical'>

In [30]:
arr[1]

Interval(20, 30, closed='right')

In [31]:
arr[:3]

[(10, 20], (20, 30], (0, 10]]
Categories (5, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 50] < (50, 100]]

In [34]:
ages["customized_age_grp"].value_counts().index

CategoricalIndex([(20, 30], (50, 100], (30, 50], (10, 20], (0, 10]], categories=[(0, 10], (10, 20], (20, 30], (30, 50], (50, 100]], ordered=True, dtype='category')

In [36]:
ages["customized_age_grp"].value_counts().values

array([6, 3, 3, 2, 2])